
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres3
      POSTGRES_DB: BOOKIPI
    volumes:
      - ./apps/api/pgdata:/postgres/data
    ports:
      - 35000:5432
  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command:
      [
        "redis-server",
        "--save",
        "20",
        "1",
        "--loglevel",
        "warning",
        "--requirepass",
        "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81",
      ]
    environment:
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
