name: Backend CI

on:
  pull_request:
    branches: [main, development]
  push:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache-dependency-path: backend/package-lock.json
      - name: Install, Build, and Test Backend
        working-directory: ./backend
        run: |
          npm ci
          npm run build
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
